// 事業者データ
export const BUSINESSES = [
  {
    id: "1",
    category: "コンサル",
    name: "Quality of Life株式会社",
    description: "１日２時間を生み出す時間戦略",
    serviceContent: "",
  },
  {
    id: "2",
    category: "保険業",
    name: "大同生命保険株式会社",
    description: "経営リスクマネージメントの専門家",
    serviceContent: "",
  },
  {
    id: "3",
    category: "保険業",
    name: "REAL LIFE株式会社",
    description: "子供の未来・資金プランナー",
    serviceContent: "",
  },
  {
    id: "4",
    category: "車点検整備",
    name: "有限会社カードック糸満",
    description: "紹介の多い車の点検整備場",
    serviceContent: "",
  },
  {
    id: "5",
    category: "美容",
    name: "Birds",
    description: "琉球統計気学とプロのヘアメイクの開運眉専門店",
    serviceContent: "",
  },
  {
    id: "6",
    category: "新車リース",
    name: "株式会社上原自動車",
    description: "新車リース専門店",
    serviceContent: "",
  },
  {
    id: "7",
    category: "レンタカー",
    name: "ホワイトワンネット株式会社",
    description: "配車・回収回収対応！便利なレンタカー屋さん",
    serviceContent: "",
  },
  {
    id: "8",
    category: "外構工事",
    name: "有限会社 丸正開発",
    description: "外構（駐車場）工事の専門家",
    serviceContent: "",
  },
  {
    id: "9",
    category: "保険業",
    name: "ひらく合同会社",
    description: "銀行融資に強い財務コンサルティング",
    serviceContent: "",
  },
  {
    id: "10",
    category: "企画制作（ウェブサイトなど）",
    name: "有限会社Trinity",
    description: "映像制作",
    serviceContent: "",
  },
  {
    id: "11",
    category: "企画制作（ウェブサイトなど）",
    name: "宇名志看板店 株式会社",
    description: "屋外広告の企画制作",
    serviceContent: "",
  },
  {
    id: "12",
    category: "美容",
    name: "株式会社モイスティーヌすみれ",
    description: "お肌診断アドバイザー",
    serviceContent: "",
  },
  {
    id: "13",
    category: "外壁塗装・防水工事",
    name: "株式会社ペイントマン",
    description: "外壁塗装・屋上防水",
    serviceContent: "実家の外壁を１５年以上塗り替えしてない方",
  },
  {
    id: "14",
    category: "体質改善",
    name: "clooney＆Ｎ",
    description: "貼るだけ体質改善",
    serviceContent: "睡眠の質が悪く体調がすぐれない方",
  },
  {
    id: "15",
    category: "コンサル",
    name: "合同会社Ｓ＆Ｎコミュニケーション",
    description: "企業を成長させるバックオフィスコンサル",
    serviceContent: "経理作業は嫁（旦那）に任せている方。",
  },
  {
    id: "16",
    category: "司法書士",
    name: "司法書士法人ロアック 糸満オフィス",
    description: "進化する司法書士軍団",
    serviceContent: "相続の悩みをどこに相談したいいかわからない方。",
  },
  {
    id: "17",
    category: "保険業",
    name: "株式会社ＪＵＳＴ",
    description: "損害保険",
    serviceContent: "大きい声では言えないが自宅で火災保険に入ってない方。",
  },
  {
    id: "18",
    category: "清掃",
    name: "おそうじ本舗 豊見城店",
    description: "エアコンクリーニングが人気の掃除屋さん",
    serviceContent: "家やオフィスの掃除をお願いしたい方。",
  },
  {
    id: "19",
    category: "不動産",
    name: "株式会社徳松産業",
    description: "トータルサポートができる賃貸管理",
    serviceContent: "アパート管理会社の対応が悪く新しい管理会社を探している。",
  },
  {
    id: "20",
    category: "企画制作（ウェブサイトなど）",
    name: "株式会社マカナ",
    description: "集客が得意なＷＥＢサイト制作",
    serviceContent: "新規事業を始めるのでホームページ会社を探している方",
  },
  {
    id: "21",
    category: "Tシャツ販売",
    name: "K´Zベース（ケイズベース）",
    description: "オリジナルTシャツ専門店",
    serviceContent: "イベントで使うTシャツ制作会社を探している方",
  },
  {
    id: "22",
    category: "不動産",
    name: "株式会社R-JAPAN",
    description: "不動産売買",
    serviceContent: "不動産売却を考えている方。",
  },
  {
    id: "23",
    category: "コンサル",
    name: "株式会社STEP",
    description: "人手不足が解消できる人材トータルコンサルタント",
    serviceContent: "",
  },
  {
    id: "24",
    category: "スポーツ関連",
    name: "うるくLabo",
    description: "シュミレーションゴルフも出来る夜型クラブ修理屋",
    serviceContent: "ゴルフクラブを自分に合うクラブに調整したい方。",
  },
  {
    id: "25",
    category: "販売業",
    name: "INFINITY STAR",
    description: "自動販売機",
    serviceContent: "冷凍販売機で収益がほしい方",
  },
  {
    id: "26",
    category: "食品",
    name: "株式会社 仁智 金家",
    description: "キムチ専門店",
    serviceContent: "韓国キムチや韓国商品の販売に興味がある方",
  },
  {
    id: "27",
    category: "販売業",
    name: "株式会社LEQUIOS",
    description: "企業専用の安定高速インターネット回線",
    serviceContent: "持ちアパートの家賃値上げをしたい",
  },
  {
    id: "28",
    category: "安全",
    name: "株式会社沖縄大日警",
    description: "施設警備業",
    serviceContent: "会社に泥棒が入った経験がある方",
  },
  {
    id: "29",
    category: "住宅建築",
    name: "エージェイエフ有限会社",
    description: "自然素材×超高性能な木造住宅",
    serviceContent: "高性能な住宅に住みたい方",
  },
  {
    id: "30",
    category: "光熱費の削減",
    name: "株式会社リネクト",
    description: "太陽光で守る、家と家計",
    serviceContent: "電気代金の削減に興味のある方",
  },
  {
    id: "31",
    category: "スポーツ関連",
    name: "Kazu",
    description: "トレーニング",
    serviceContent: "子供が部活でケガをした。予防とパフォーマンスアップトレーニングに興味がある方。",
  },
  {
    id: "32",
    category: "運輸",
    name: "株式会社 新光運輸",
    description: "商業向け輸送",
    serviceContent: "プレハブやコンテナの運輸ができる運送屋さんを探している。",
  },
] as const;

// カテゴリ名で事業者を取得
export function getBusinessesByCategory(categoryName: string) {
  return BUSINESSES.filter((b) => b.category === categoryName);
}

// IDで事業者を取得
export function getBusinessById(id: string) {
  return BUSINESSES.find((b) => b.id === id);
}
